name: Deploy Chat Backend on EC2

on: 
  push: 
    branches:
      - master

jobs:
  deploy: 
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with: 
          ssh-private-key: ${{secrets.EC2_SSH_KEY}}

      - name: Deploy application
        env:
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
          DATABASE_URI: ${{ secrets.DATABASE_URI }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          URL: ${{ secrets.URL }}
        run: |
          ssh -o StrictHostKeyChecking=no $USER@$HOST << 'EOF'
          
            cd /home/ubuntu/chat-app-backend

            # if [ ! -d "chat-app-backend" ]; then
            #   echo "Repository not found, cloning..."
            #   git clone https://github.com/yourHighness11/chat-app-backend
            # fi

            git pull origin master

            npm install --production

            
            # Ensure pm2 is installed
            # if ! command -v pm2 &> /dev/null
            # then
            #   echo "pm2 could not be found, installing..."
            #   npm install pm2 -g
            # fi

            # Export environment variables
            export DATABASE_URI="${DATABASE_URI}"
            export JWT_SECRET_KEY="${JWT_SECRET_KEY}"
            export URL="${URL}"

            # Check if the app is running with pm2, then restart or start
            pm2 list | grep "chat-app-new" || pm2 start server.js --name "chat-app-new"
            pm2 restart "chat-app-new"
            pm2 save --force
          EOF

          

          

          

      
    
