name: Deploy Chat Backend on EC2

on: 
  push: 
    branches:
      - master

jobs:
  deploy: 
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with: 
          ssh-private-key: ${{secrets.EC2_SSH_KEY}}

      - name: Deploy application
        env:
          HOST: ${{secrets.EC2_HOST}}
          USER: ${{secrets.EC2_USER}}
        run: |
          ssh -o StrictHostKeyChecking=no $USER@$HOST << 'EOF'
          
            cd /home/ubuntu/chat-app-backend

            git pull origin main

            npm install --production

            pm2 restart all || pm2 start app.js
          EOF

          

          

          

      
    
